import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import PrelineScript from '@/components/providers/PrelineProviders';
import ToastProviders from '@/components/providers/ToastProviders';
import AuthProviders from '@/components/providers/AuthProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrelineScript />
      <body className={inter.className}>
        <ToastProviders />
        <AuthProviders>{children}</AuthProviders>
      </body>
    </html>
  );
}
